version: '3.7'

services:
  nginx:
    image: nginx:1.16.1
    container_name: ${PROJECT}_nginx
    volumes:
      - ./docker/nginx/app.nginx:/etc/nginx/conf.d/default.conf
      - ./www/app:/var/www/app
    ports:
      - ${PORT_NGINX-80}:80
    depends_on:
      - lara-php
  lara-php:
    dns: 8.8.8.8
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./www/app:/var/www/app
    ports:
      - 9909:9909
    depends_on:
      - mysql
      - elastic
    env_file:
      - .env
  mysql:
    hostname: mysql
    image: mysql:8
    container_name: ${PROJECT}_mysql
    ports:
      - ${PORT_MYSQL-3306}:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/x-conf.cnf:/etc/mysql/conf.d/x-conf.cnf
    env_file:
      - .env
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - mysql:db
      ports:
          - "8080:80"
      environment:
          MYSQL_ROOT_PASSWORD: root
      depends_on:
          - mysql
  elastic:
    image: elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  ngrok:
    image: wernight/ngrok
    command: ngrok http --region=eu ${PROJECT}_nginx:80
    ports:
      - 4040:4040
